### ISSUE TITLE
Missing dep on toml?

### ISSUE THREAD

**Issue by jreese** [omnilib/attribution#14]
### Description

```shell-session
(venv37) jreese@garbodor ~/scratch » pip install attribution
Collecting attribution
  Downloading attribution-1.2.0-py3-none-any.whl (12 kB)
Requirement already satisfied: packaging in ./venv37/lib/python3.7/site-packages (from attribution) (20.4)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting attrs
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting jinja2
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Requirement already satisfied: pyparsing>=2.0.2 in ./venv37/lib/python3.7/site-packages (from packaging->attribution) (2.4.7)
Requirement already satisfied: six in ./venv37/lib/python3.7/site-packages (from packaging->attribution) (1.15.0)
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp37-cp37m-macosx_10_6_intel.whl (18 kB)
Installing collected packages: click, attrs, MarkupSafe, jinja2, attribution
Successfully installed MarkupSafe-1.1.1 attribution-1.2.0 attrs-20.2.0 click-7.1.2 jinja2-2.11.2

(venv37) jreese@garbodor ~/scratch » rehash
(venv37) jreese@garbodor ~/scratch » attribution --help
Traceback (most recent call last):
  File "/Users/jreese/scratch/venv37/bin/attribution", line 5, in <module>
    from attribution.main import main
  File "/Users/jreese/scratch/venv37/lib/python3.7/site-packages/attribution/main.py", line 12, in <module>
    from .generate import Changelog
  File "/Users/jreese/scratch/venv37/lib/python3.7/site-packages/attribution/generate.py", line 8, in <module>
    from .project import Project
  File "/Users/jreese/scratch/venv37/lib/python3.7/site-packages/attribution/project.py", line 9, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
```

### Details

* OS: macOS
* Python version: 3.7.5
* attribution version: 1.2.0
* Can you repro on main?
* Can you repro in a clean virtualenv? yes

**Comment by thatch** [comment]
Consider adding something like this to CI?

```
python -m pessimist --fast --requirements= -c "attribution --help" .
```

The `--requirements=` makes it only keep the deps from metadata; although you can't run the full tests that way.  Example at https://github.com/facebookincubator/Bowler/pull/131/files
