### ISSUE TITLE
Setup pessimist maybe?

### ISSUE THREAD

**Issue by amyreese** [omnilib/attribution#18]
### Description

Add pessimist to `make test` or CI or something.

**Comment by jreese** [comment]
@thatch I tried running the command you had in #14, but it failed on my local machine:

```
(.venv) jreese@legion ~/workspace/attribution main  ‹2› » python -m pessimist --fast --requirements= -c "attribution --help" .
Requirement already satisfied: flit_core<4,>=3 in ./.venv/lib/python3.8/site-packages (3.0.0)
Requirement already satisfied: pytoml in ./.venv/lib/python3.8/site-packages (from flit_core<4,>=3) (0.1.21)
WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Summary
=======
Variable ['attrs', 'click', 'jinja2', 'packaging', 'tomlkit']
Fixed []

Versions
========
attrs ['15.0.0', '20.3.0']
click ['0.1', '7.1.2']
jinja2 ['2.0', '2.11.2']
packaging ['14.0', '20.4']
tomlkit ['0.1.0', '0.7.0']

FAIL min: Install failed
  $ /var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/tmpip3gh008/bin/python -m pip install attrs==15.0.0 click==0.1 jinja2==2.0 packaging==14.0 tomlkit==0.1.0Collecting attrs==15.0.0
    Downloading https://files.pythonhosted.org/packages/a2/f6/97806e9f6fe4d2b6f04d947a9a4ac36b17d1f4bc48cbebfcd27d5c198d33/attrs-15.0.0.tar.gz
  Collecting click==0.1
    Downloading https://files.pythonhosted.org/packages/82/e9/39bc04e46ac4dc16f60d3c95d2a8238f8a86a738ecab723755470e1486d1/click-0.1-py2.py3-none-any.whl
  Collecting jinja2==2.0
    Downloading https://files.pythonhosted.org/packages/01/82/b2ed16b1cbea5ddbf1462fb65cf67ce7cd780dc1b6a6f0244f1387fa007d/Jinja2-2.0.tar.gz (523kB)
      ERROR: Command errored out with exit status 1:
       command: /private/var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/tmpip3gh008/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/pip-install-wl5xuufp/jinja2/setup.py'"'"'; __file__='"'"'/private/var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/pip-install-wl5xuufp/jinja2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
           cwd: /private/var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/pip-install-wl5xuufp/jinja2/
      Complete output (6 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/3c/b8ndz8l537b0xp_p8vljfc180000gn/T/pip-install-wl5xuufp/jinja2/setup.py", line 91
          except CCompilerError, x:
                               ^
      SyntaxError: invalid syntax
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 20.2.4 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by thatch** [comment]
jinja2==2.0 (released in 2008) has py2 syntax; this is a legal choice given

```
[tool.flit.metadata]
requires = ["attrs", "click", "jinja2", "packaging", "tomlkit"]
```
The error message is not very clear because the failure is in the _install_ step, and you passed `--fast` which just fails.

Rerunning as

```
$ python -m pessimist --requirements= -c "python -m attribution.main --help" .
...
Final test
==========
{'attrs': <Version('19.2.0')>, 'click': <Version('0.1')>, 'jinja2': <Version('2.7')>, 'packaging': <Version('14.0')>, 'tomlkit': <Version('0.1.0')>}
OK   min
Suggest narrowing: attrs>=19.2.0
Suggest narrowing: jinja2>=2.7
```

(Note the `attribution` command isn't available, so had to run it with `-m` -- it doesn't actually install the project under test unless you include something that does in the `-c`)
