### ISSUE TITLE
"AttributeError: 'OutOfOrderTableProxy' object has no attribute 'append'" on `attribution init`

### ISSUE THREAD

**Issue by sfermigier** [omnilib/attribution#182]
### Description

```
~/git/abilian-sbe-monorepo$ attribution init
Project name [abilian-sbe-monorepo]:
Package namespace [abilian_sbe_monorepo]: abilian
Use __version__.py file [Y/n]: n
Use GPG signed tags [Y/n]: n
Traceback (most recent call last):
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/bin/attribution", line 8, in <module>
    sys.exit(main())
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fermigier/.cache/pypoetry/virtualenvs/abilian-sbe-Ez3cmVwm-py3.10/lib/python3.10/site-packages/attribution/main.py", line 63, in init
    tool.append("attribution", table)
AttributeError: 'OutOfOrderTableProxy' object has no attribute 'append'
```

### Details

* OS: Linux or MacOS
* Python version: 3.10
* attribution version: latest
* Can you repro on main? not tried
* Can you repro in a clean virtualenv? yes

**Comment by amyreese** [comment]
Spent a little bit of time debugging this (assuming your project is https://github.com/abilian/abilian-sbe-monorepo). It looks like this is a limitation of tomlkit, triggered by your `pyproject.toml` placing its `[build-system]` table in between the various `[tool.<whatever>]` tables, because the elements of the `[tool]` namespace are not contiguous. 

Unfortunately I don't think there's anything reasonable I can do in attribution to work around this limitation.

If you move your `[build-system]` table to the top of your `pyproject.toml`, then attribution is able to correctly modify the file to add its own `[tool.attribution]` table. Alternatively, if you manually add a `[tool.attribution]` table at the end of your existing pyproject file, that is also sufficient to allow attribution and tomlkit to modify the necessary parts of the file.  

You could also skip the init step entirely, and manually configure attribution by referencing the [user guide on configuration](https://attribution.omnilib.dev/en/stable/guide.html#configuration).
