### ISSUE TITLE
The `attribution init` command fails

### ISSUE THREAD

**Issue by AIGeneratedUsername** [omnilib/attribution#26]
### Description
```
(venv) sam@sam-tobefilledbyoem:/PyCharmProjects/my_project$ attribution init
Project name [my_project]: 
Package namespace [my_project]: 
Use __version__.py file [Y/n]: Y
WARNING:attribution.tag:Skipping tag fixed_coder
WARNING:attribution.tag:Skipping tag fixed_logging
WARNING:attribution.tag:Skipping tag improved_tests
WARNING:attribution.tag:Skipping tag june_25th
WARNING:attribution.tag:Skipping tag major_refactor
WARNING:attribution.tag:Skipping tag ready_for_deployment_tests
WARNING:attribution.tag:Skipping tag smaller_fixes
WARNING:attribution.tag:Skipping tag working_rate_limit
Traceback (most recent call last):
  File "/PyCharmProjects/my_project/venv/bin/attribution", line 8, in <module>
    sys.exit(main())
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/attribution/main.py", line 63, in init
    VersionFile(project).write()
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/attribution/generate.py", line 26, in write
    content = self.generate()
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/attribution/generate.py", line 22, in generate
    output = template.render(project=self.project, tags=tags, len=len)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/PyCharmProjects/my_project/venv/lib/python3.9/site-packages/attribution/project.py", line 40, in latest
    return self.tags[0]
IndexError: list index out of range


```

### Details

* OS: Lubuntu
* Python version: 3.9
* attribution version: 1.4.0
* Can you repro on main? - Not tried
* Can you repro in a clean virtualenv? - Not tried

**Comment by jreese** [comment]
I suspect this might be an edge case hit when a project does not have any version tags recognized by attribution. Can you confirm this? A paste of `git tag | grep "^v"` should be sufficient.

**Comment by jreese** [comment]
I tested on a freshly-created git repo and got a similar stack trace:

```
(.venv) jreese@mordin ~/scratch » cd test-attribution
(.venv) jreese@mordin ~/scratch/test-attribution » git init
Initialized empty Git repository in /Users/jreese/scratch/test-attribution/.git/
(.venv) jreese@mordin ~/scratch/test-attribution master  » attribution init
Project name [test-attribution]:
Package namespace [test-attribution]: test_attribution
Use __version__.py file [Y/n]:
Traceback (most recent call last):
  File "/Users/jreese/workspace/attribution/.venv/bin/attribution", line 8, in <module>
    sys.exit(main())
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/attribution/main.py", line 63, in init
    VersionFile(project).write()
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/attribution/generate.py", line 26, in write
    content = self.generate()
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/attribution/generate.py", line 22, in generate
    output = template.render(project=self.project, tags=tags, len=len)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/Users/jreese/workspace/attribution/.venv/lib/python3.9/site-packages/attribution/project.py", line 40, in latest
    return self.tags[0]
IndexError: list index out of range
```

**Comment by jreese** [comment]
The 1.5.1 release contains fixes for this. Thanks for reporting it!
