### ISSUE TITLE
Repo state unknown error

### ISSUE THREAD

**Issue by bastienboutonnet** [omnilib/attribution#31]
### Description
I was trying out the package for the first time because it looks really good for my needs but I ran into an error that I'm having a hard time understanding.

Here's the command I ran + full traceback.

```bash
(dbt-sugar-lJO0x__U-py3.9) ➜  dbt-sugar git:(release/0.0.0-b.0) ✗ attribution tag -m "0.0.0-b.0" 0.0.0-b.0
Bump failed, version message in /Users/bastienboutonnet/repos/dbt-sugar/.attribution-0.0.0b0.txt, repo state unknown ¯\_(ツ)_/¯
Traceback (most recent call last):
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/bin/attribution", line 8, in <module>
    sys.exit(main())
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/attribution/main.py", line 138, in tag_release
    changelog = Changelog(project).write()
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/attribution/generate.py", line 26, in write
    content = self.generate()
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/attribution/generate.py", line 22, in generate
    output = template.render(project=self.project, tags=tags, len=len)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 8, in top-level template code
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/attribution/tag.py", line 53, in message
    out = sh(f"git cat-file tag {self.name}")
  File "/Users/bastienboutonnet/Library/Caches/pypoetry/virtualenvs/dbt-sugar-lJO0x__U-py3.9/lib/python3.9/site-packages/attribution/helpers.py", line 19, in sh
    p = subprocess.run(
  File "/Users/bastienboutonnet/.pyenv/versions/sugar_conda/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('git', 'cat-file', 'tag', 'v0.0.0-alpha.10')' returned non-zero exit status 128.
```

My only hunch is that maybe it's not liking my tag formats with the alpha bit in it?

### Details

* OS: Big Sur
* Python version: 39
* attribution version: 1.5.2
* Can you repro on main? yes 
* Can you repro in a clean virtualenv? yes

**Comment by jreese** [comment]
Based on your shell prompt, I'm guessing that your existing version tags don't have a "v" prefix on them. attribution is expecting them, and is failing to get about your tags because it's looking for the wrong names rather than recording what the exact tag name was and looking that up.

**Comment by bastienboutonnet** [comment]
@jreese thanks for getting back to me on this.
I think this might not be the case as my tags are `v`-prefixed here's the output of `git tags -l`
```
v0.0.0-alpha.0
v0.0.0-alpha.1
v0.0.0-alpha.10
v0.0.0-alpha.2
v0.0.0-alpha.3
v0.0.0-alpha.4
v0.0.0-alpha.5
v0.0.0-alpha.6
v0.0.0-alpha.7
v0.0.0-alpha.8
v0.0.0-alpha.9
v0.0.0-beta.0
```

**Comment by jreese** [comment]
Is this a public repo that I can clone and test locally with?

**Comment by bastienboutonnet** [comment]
@jreese yes absolutely. Thanks a lot for going out of your way with this. The repo is here: https://github.com/bitpicky/dbt-sugar

**Comment by jreese** [comment]
So the issue is specifically with your `v0.0.0-alpha.10` tag and how it's stored in your git repo. You might want to consider re-tagging it and see if that resolves the issue.

Compare git's knowledge of alpha.10:
```
(.venv) jreese@mordin ~/workspace/dbt-sugar main  » git cat-file tag v0.0.0-alpha.10
fatal: git cat-file v0.0.0-alpha.10: bad file

(.venv) jreese@mordin ~/workspace/dbt-sugar main  ‹128› » git show v0.0.0-alpha.10 | head
commit 22a1c7881871eb76aa951b70b725eb9baea713bf
Author: Bastien Boutonnet <bastien.b1@gmail.com>
Date:   Sun Mar 28 17:54:57 2021 +0200

    Bump version: 0.0.0-alpha.9 → 0.0.0-alpha.10

diff --git a/.bumpversion.cfg b/.bumpversion.cfg
index f8a46ee..40798a4 100644
--- a/.bumpversion.cfg
+++ b/.bumpversion.cfg
```

Versus alpha.9:
```
(.venv) jreese@mordin ~/workspace/dbt-sugar main  » git cat-file tag v0.0.0-alpha.9
object b586358ad00e801a78b3e8ae1a03d5704df45f11
type commit
tag v0.0.0-alpha.9
tagger Bastien Boutonnet <bastien.b1@gmail.com> 1616523574 +0100

Bump version: 0.0.0-alpha.8 → 0.0.0-alpha.9

(.venv) jreese@mordin ~/workspace/dbt-sugar main  » git show v0.0.0-alpha.9 | head
tag v0.0.0-alpha.9
Tagger: Bastien Boutonnet <bastien.b1@gmail.com>
Date:   Tue Mar 23 19:19:34 2021 +0100

Bump version: 0.0.0-alpha.8 → 0.0.0-alpha.9

commit b586358ad00e801a78b3e8ae1a03d5704df45f11
Author: Bastien Boutonnet <bastien.b1@gmail.com>
Date:   Tue Mar 23 19:19:31 2021 +0100
```

I'm guessing that alpha.10 is not an annotated tag? Eg, running just `git tag <name>` instead of `git tag -a <name>` and supplying a message. If that's the case, I would suggest retagging it with `git tag --force -a v0.0.0-alpha.10 v0.0.0-alpha.10`. That resolved the issue on my local checkout.

**Comment by bastienboutonnet** [comment]
Oh that's interesting. I rarely add descriptions but I think I created the tag on a branch and then merged that branch with squash. Maybe it messed things up... Ok I think I'll try in the next build :) thanks a lot for looking into this. Really appreciate it!
